In [1]:
import pandas as pd
from transformers import T5Tokenizer, Trainer, TrainingArguments, T5ForConditionalGeneration

In [3]:
train_data = pd.read_csv("samsum-train.csv")
val_data = pd.read_csv("samsum-validation.csv")

In [4]:
train_data.head()

,id,dialogue,summary
0,13818513,Amanda: I baked cookies. Do you want some?\r\...,Amanda baked cookies and will bring Jerry some...
1,13728867,Olivia: Who are you voting for in this electio...,Olivia and Olivier are voting for liberals in ...
2,13681000,"Tim: Hi, what's up?\r\nKim: Bad mood tbh, I wa...",Kim may try the pomodoro technique recommended...
3,13730747,"Edward: Rachel, I think I'm in ove with Bella....",Edward thinks he is in love with Bella. Rachel...
4,13728094,Sam: hey overheard rick say something\r\nSam:...,"Sam is confused, because he overheard Rick com..."

In [5]:
val_data.head()

,id,dialogue,summary
0,13817023,"A: Hi Tom, are you busy tomorrow’s afternoon?\...",A will go to the animal shelter tomorrow to ge...
1,13716628,Emma: I’ve just fallen in love with this adven...,Emma and Rob love the advent calendar. Lauren ...
2,13829420,Jackie: Madison is pregnant\r\nJackie: but she...,Madison is pregnant but she doesn't want to ta...
3,13819648,Marla: <file_photo>\r\nMarla: look what I foun...,Marla found a pair of boxers under her bed.
4,13728448,Robert: Hey give me the address of this music ...,Robert wants Fred to send him the address of t...

In [6]:
train_data["dialogue"][0]

"Amanda: I baked  cookies. Do you want some?\r\nJerry: Sure!\r\nAmanda: I'll bring you tomorrow :-)"

In [7]:
train_data.sample(10)

,id,dialogue,summary
3050,13816234,Joe: do you feel like going to the cinema?\r\n...,Joe and Kathy will meet at the cinema at 6 pm ...
9047,13864652,Eve: I don't like Martha\nErick: Me neither\nB...,Eve and Erick are not fond of Martha.
8379,13865246,Gina: <file_photo>\nGina: or\nGina: <file_phot...,Gina has to wear glasses. She has two pairs to...
4167,13862331,Marie: check out this blog for some romantic s...,Marie recommended Laura a blog with romantic p...
10200,13729829,"Leila: Darling, my parents are inviting us for...","Brat wanted to go fishing, but Leila's parents..."
1814,13594116-1,Greg: Hi! Have a look at that photo.\r\nWill: ...,Greg and Will make comments on a photo. Will a...
5603,13681067,"Jim: Hey, how do you move the screen to the le...","Thanks to George, Jim knows now how to move th..."
3375,13821457,"Jack: Hey guys, any plans for this weekend?\r\...","Jack, Kasia and Wojtek will go to a concert th..."
3478,13681544,Nina: Thank you for the flowers! Beautiful!\r\...,Tim surprised Nina with flowers after they spe...
4517,13828002,"Jake: Hello 🙂\r\nJuliet: Jake, long time no se...","Jake, Kelly, Greg and Tom want to go camping o..."

In [8]:
train_data.shape

(14732, 3)

In [9]:
val_data.shape

(818, 3)

In [10]:
#Random Sampling
train_data = train_data.sample(n=4000, random_state=42).reset_index(drop=True)
val_data = val_data.sample(n=500, random_state=42).reset_index(drop=True)

In [11]:
train_data.shape

(4000, 3)

## Data Preprocessing

In [12]:
import re

def clean_data(text):
    text = re.sub(r"\r\n", " ", text) #lines"
    text = re.sub(r"\s+", " ", text) # Spaces
    text = re.sub(r"<.*?>", "", text) # HTML tags
    text = text.strip().lower()
    return text

In [13]:
train_data["dialogue"] = train_data["dialogue"].apply(clean_data)
train_data["summary"] = train_data["summary"].apply(clean_data)

In [14]:
val_data["dialogue"] = val_data["dialogue"].apply(clean_data)
val_data["summary"] = val_data["summary"].apply(clean_data)

In [15]:
train_data["dialogue"][0]

"violet: hi! i came across this austin's article and i thought that you might find it interesting violet:  claire: hi! :) thanks, but i've already read it. :) claire: but thanks for thinking about me :)"